---
- name: Deploy YOLO Application
  hosts: gcp_hosts
  gather_facts: false
  become: true
  vars:
    client_image: mngaruiya/yoloreactapiclient:v1.0.1 
    backend_image: mngaruiya/yolodb_backend:v1.0.1
    app_folder: /opt/yolo

  tasks:
    - name: Update the cache
      apt:
        update_cache: yes
        upgrade: yes

    - name: Clone the repository
      git:
        repo: https://github.com/mngaruiya/WEEK9A.git
        dest: /opt/yolo

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install Docker dependencies
      apt:
        name:
          - "apt-transport-https"
          - "ca-certificates"
          - "curl"
          - "software-properties-common"
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Start Docker containers
      command: docker-compose up -d
      args:
        chdir: /opt/yolo